version: 2
multi-ecosystem-groups:
  ci:
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    commit-message:
      prefix: ci
updates:
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: ci
  - package-ecosystem: docker
    directory: /.github/actionlint
    patterns: ["*"]
    multi-ecosystem-group: ci
  - package-ecosystem: rust-toolchain
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: ci
