[windows.tcp]
ttl = 128
mss = 1460
window_size = 64240
df = true
window_scale = 8
no_delay = true
options = [2, 1, 3, 1, 1, 4]

[macos.tcp]
ttl = 64
mss = 1460
window_size = 65535
df = true
window_scale = 6
no_delay = true
options = [2, 1, 3, 1, 1, 8, 4, 0]

[linux.tcp]
ttl = 64
mss = 1460
window_size = 64240
df = true
window_scale = 10
no_delay = true
options = [2, 4, 8, 1, 3]

[android.tcp]
ttl = 64
mss = 1460
window_size = 65535
df = true
window_scale = 7
no_delay = true
options = [2, 4, 8, 1, 3]

[ios.tcp]
ttl = 64
mss = 1460
window_size = 65535
df = true
window_scale = 0
no_delay = false
options = [2, 4, 8, 1, 3]
