[package]
name = "leyline-tls"
description = "BoringSSL TLS connector with fingerprint control"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
leyline-tcp = { path = "../tcp" }
leyline-profile = { path = "../profile" }
boring = { workspace = true }
boring-sys = { workspace = true }
tokio-boring = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
socket2 = { workspace = true }
libc = "0.2"
lru = "0.16.3" # RUSTSEC-2026-0002 fix
brotli = "8"
url = { workspace = true }

[lints]
workspace = true
