[package]
name = "leyline-core"
description = "Session, transport, request builder, and response types"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
leyline-tls = { path = "../tls" }
leyline-h2 = { path = "../h2" }
leyline-pool = { path = "../pool" }
leyline-profile = { path = "../profile" }
leyline-tcp = { path = "../tcp" }
leyline-cookies = { path = "../cookies" }
leyline-audit = { path = "../audit" }
leyline-quic = { path = "../quic" }
tokio-tungstenite = { workspace = true }
tungstenite = { workspace = true }
sha1 = { workspace = true }
futures-util = "0.3"
http = "1"
tokio-boring = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
flate2 = "1"
brotli = "8"
zstd = "0.13"

[lints]
workspace = true
